networks:
  cssninja-services:
    external: true

services:
  masonry-demo:
    image: digisquad/cssninja.masonry-demo:latest
    networks:
      - cssninja-services
    restart: 'unless-stopped'
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.masonry-demo.entrypoints: 'http'
      traefik.http.routers.masonry-demo.rule: 'Host(`masonry.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.masonry-demo.middlewares: 'https-redirect@file'
      traefik.http.services.masonry-demo-https.loadbalancer.server.port: 8080
      traefik.http.routers.masonry-demo-https.rule: 'Host(`masonry.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.masonry-demo-https.tls: true
      traefik.http.routers.masonry-demo-https.entrypoints: 'https'
      traefik.http.routers.masonry-demo-https.tls.certresolver: 'http'

